version: '3'
services:

  poll:
    build: ./poll
    links: 
      - redis
    restart: always
    environment:
      - REDIS_HOSTNAME=redis
    ports:
      - 5000:80
    networks:
      - poll-tier



  
  result: 
    build: ./result
    links: 
      - db
    restart: always
    environment:
      - DB_HOSTNAME=db
    networks:
      - result-tier
    ports:
      - 5001:80


  worker:
    build: ./worker
    links:
      - redis
      - db
    restart: always

    environment:
      - DB_HOSTNAME=db
      - REDIS_HOSTNAME=redis

    networks:
      - back-tier
    ports:
      - 5002:80

  redis:
    image: "redis:alpine"
    restart: always
    expose:
      - "6379"
    environment:
      - POLL_HOSTNAME=poll
      - WORKER_HOSTNAME=worker
    networks:
      - poll-tier
      - back-tier


  db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    
   # command: '--init-file ./lol/schema.sql'
    networks:
      - result-tier
      - back-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/usr/share/db

      
    environment:
      - WORKER_HOSTNAME=worker
      - RESULT_HOSTNAME=result
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres

volumes:
  db-data:
    driver: local


networks:
  poll-tier:
    driver: bridge
  result-tier:
    driver: bridge
  back-tier:
    driver: bridge
